### ISSUE TITLE
Thumbnails Caches for Internal Images As Well?

### ISSUE THREAD

**Issue by yuboWw** [Qbject/obsidian-canvas-link-optimizer#3] opened 2024-10-24 02:03 UTC
I just came across this plugin while looking for enhancement plugins for Canvas. I think this is a **_fantastic_** creation to improve performance of Canvas. But, I do think, just in general, images are more common than transcluded webpages. I'm not familiar with the technicality in that regard, but i'm curious to know:

- Can what this plugin does also be applied to internal media files, like images? ((That will be a life saver !!
- If internal images are more technically difficult than web embeds, what is the barrier, mechanism wise?

I also proposed this idea as [a feature request on the official forum](https://forum.obsidian.md/t/canvas-option-zoom-threshold-for-hiding-card-content-to-also-apply-to-non-text-elements-esp-images-to-improve-performance-on-media-heavy-large-canvases/90210)

@Qbject 
thanks for this,
yubo

**Comment by Qbject** [comment] 2024-10-24 08:45
@yuboWw thanks for the feedback, I appreciate it!

I've noticed some performance issues related to images, but in my canvases, there's about 10 times fewer images than web embeds, so I didn't pay much attention to this. But this seems to be a common issue, so I took a look into it.

The current web embeds approach would need a considerable rework to make it work with images (it's doable though), so I've come up with a much simpler idea - just hide images while zoomed out (like other node types).

Here's my quick dirty solution to this:
```javascript
const nodes = app.workspace.getActiveFileView().canvas.nodes.values();
for(const node of nodes){
    if(node.getData().type === "file"){
        delete node.__proto__.updateBreakpoint;
        node.updateBreakpoint();
    }
}
```

Just open *any* canvas with at least a single image in it and run this code in the developer's console (ctrl+shift+I -> Console). Once done, all the media on all canvases should automatically unload until you restart Obsidian.

Please let me know what you think. If this works for you, I can make this into a proper separate plugin or add as a feature to this one.

P.S. From my observations, the easiest way to kill canvas performance is by PDF files. So make sure you don't include them directly into a canvas.

**Comment by yuboWw** [comment] 2024-10-25 11:06
> @yuboWw thanks for the feedback, I appreciate it!
> 
> 
> 
> I've noticed some performance issues related to images, but in my canvases, there's about 10 times fewer images than web embeds, so I didn't pay much attention to this. But this seems to be a common issue, so I took a look into it.
> 
> 
> 
> The current web embeds approach would need a considerable rework to make it work with images (it's doable though), so I've come up with a much simpler idea - just hide images while zoomed out (like other node types).
> 
> 
> 
> Here's my quick dirty solution to this:
> 
> ```javascript
> 
> const nodes = app.workspace.getActiveFileView().canvas.nodes.values();
> 
> for(const node of nodes){
> 
>     if(node.getData().type === "file"){
> 
>         delete node.__proto__.updateBreakpoint;
> 
>         node.updateBreakpoint();
> 
>     }
> 
> }
> 
> ```
> 
> 
> 
> Just open *any* canvas with at least a single image in it and run this code in the developer's console (ctrl+shift+I -> Console). Once done, all the media on all canvases should automatically unload until you restart Obsidian.
> 
> 
> 
> Please let me know what you think. If this works for you, I can make this into a proper separate plugin or add as a feature to this one.
> 
> 
> 
> P.S. From my observations, the easiest way to kill canvas performance is by PDF files. So make sure you don't include them directly into a canvas.




@Qbject 

thanks for your efforts!

i tried the temporary solution, it works, the lagging issue is gone. this is nice. 

because all images are unloaded, when zoomed out, it's not showing a birds-eye-view of the canvas and how the images are arranged to show their content-wise relationship and abstract content, which is the intuitive/complete solution to this issue.

as you mentioned, i'd also imagine this is a common problem to all canvas users, especially for visual art related projects where there are many images on the canvas, as it is my case, but could also for anything that's visual heavy 

i'm so glad and i very much appreciate that you offered to integrate this into the webpages plugin you made or to make it into a standalone one; either case, i would love to follow closely and hear from the progress in that pursuit. pls lmk!

thank you so much for your efforts to the community!

**Comment by Qbject** [comment] 2024-10-28 19:06
@yuboWw 

I'm back with the news. So, I started to develop a tool for images downscaling and this got me into a quite a journey. Long story short:

As appears, images themselves don't have a significant impact on performance (my laptop could easily render 432 images 3840x2160px). Instead I found a few bugs in Obsidian that were ruining the canvas performance. I've already [notified](https://forum.obsidian.md/t/canvas-performance-bugs/90641) the developers about my discovery, so hopefully we'll eventually get an update resolving this.

Also I've [developed own patch](https://github.com/Qbject/obsidian-canvas-performance-patch) for these issues in form of a plugin. Feel free to install it (it's not in the plugin library, so you'll need to do it manually) and let me know if it works.

P.S. I've released the new update for canvas-link-optimizer plugin making link thumbnails visible at any zoom level, so if you're using it, you may want to update.

**Comment by yuboWw** [comment] 2024-11-05 15:08
Hey, sorry for the late reply. Thank you so much for bringing this to the developer team's attention with such technical details! They responded so quickly with the 1.7.5 desktop update, and that made me happy and trust the tool even more.

I have tried the patch plugin for myself and my younger sister, whom I'm trying to teach to use Obsidian for her work as well. She's in visual art, so she has a lot of images in her canvases, and this lagging issue was really painful for both of us.

But as i was testing, I couldn't really tell what it is exactly that's improving the performance, the patch plugin, or the official 1.7.5 release on desktop. I saw in your forum post, @WhiteNoise replied that one of the two issues would be fixed in 1.7.5, which I have already installed. But then I also run the plugin, and the lagging issue has been improved significantly. It's so much better now!

Has 1.7.5 indeed fixed the lagging issue you identified partially, specifically with images embeds? The changelog mentioned "`Improved render performance of Canvas when there are many nodes on the screen.`", is this it, and what @WhiteNoise meant? Does this mean that all known performance issues will be fixed until client 1.8.0 according to @WhiteNoise, and until then, it is still best to run with the patch plugin?

Thanks again for your altruistic work!
I'm certain that this is tremendously helpful for not only me and my sister, but the many users in the Obsidian community.

**Comment by Qbject** [comment] 2024-11-06 08:27
Hi @yuboWw, I'm glad it's working as intended!

The 1.7.5 indeed fixed only one of the two issues, so the images are still laggy. So, yes, the patch plugin is still helpful until the Obsidian team fully resolves the second issue.

**Comment by yuboWw** [comment] 2024-11-06 09:39
@Qbject thanks for confirming that. i just tested it again last night, in a fresh environment, without the patch plugin, 1.7.5 client still experiences quite severe lagging, but once i enable the plugin and then disable it, the improvement seems to stick around, meaning when the plugin is disabled after enabling it once, there is still noticeable improvement. i'm kind of curious, am i observing this accurately?

**Closed** 2024-11-19 14:28 UTC
